#!/bin/bash
#$ -V
#$ -S /bin/bash
#$ -N gi_pre
#$ -cwd
#$ -o /u/home/p/parkyj/nobackup-eeskin2/bipolar_hipSTR/orig/filtered/multiallelic/set.me.missing.$TASK_ID.out
#$ -j y
#$ -m n
#$ -l h_data=15G,h_rt=6:00:00,highp
#$ -t 1-22

chr=$SGE_TASK_ID

java=/usr/bin/java
javacp=/u/home/p/parkyj/nobackup-eeskin2/scripts/java
vcftools=/u/home/p/parkyj/softwares/vcftools_0.1.13/bin/vcftools
pedcheck=/u/home/p/parkyj/bin/pedcheck

origdir=/u/home/p/parkyj/nobackup-eeskin2/scripts/bipolar_pedinfo
pedinfo=$origdir/pedinfo.txt
pedstruct=$origdir/PedStructSeqID.txt
idmapfile=$origdir/PedStructSeqID.txt
familyfile=$origdir/family.txt

#change
dir=/u/home/p/parkyj/nobackup-eeskin2/bipolar_hipSTR/orig/filtered/multiallelic
name=multiallelic.recode
vcf=$dir/chr$chr.$name.vcf.gz
outdir=$dir/memissing
mkdir $outdir
outdir=$outdir/chr$chr
mkdir $outdir

seqfam=/u/nobackup/eeskin2/jhsul/bipolar/gvcf_batch_final/polymutt_indel/chr1/0/plink/bp.churchill.hc.454indiv.vep.qc1.nomono.biallele.gwasqc.polymutt.indel.chr.1.region.0.fam

zcat $dir/chr$chr.$name.vcf.gz | head -n 50 | grep '#' > $outdir/head.chr$chr
zcat $dir/chr$chr.$name.vcf.gz | grep -v '#' > $outdir/chr$chr.tmp
split -d -l 10000 $outdir/chr$chr.tmp $outdir/chr$chr.
rm -f $outdir/chr$chr.tmp
for y in `ls $outdir/chr$chr.*`; \
do cat $outdir/head.chr$chr $y > $y.$name; \
rm -f $y; done
rm -f $outdir/head.chr$chr

for prefix in `ls $outdir/chr$chr.*.$name`; do
    gzip $prefix;
    $java -Xmx10G -cp $javacp ConvertVCFToLinkage $pedinfo F A F T $pedstruct T 7 0:1 $prefix.gz $prefix;

    while IFS=' ', read xx yy; do
	family=$xx
	pedig=$yy

	$pedcheck -2 -m -p $prefix.$pedig.ped -n $prefix.marker -b $prefix.$pedig.level.1
    
	$java -Xmx10G -cp $javacp SetLinkageFileMEMissingPedCheck2 $prefix.$pedig.ped $prefix.marker $prefix.$pedig.level.1.pedcheck.err $prefix.$pedig.level.1.memissing.ped $prefix.$pedig.level.1.pedcheck.mestat

	$pedcheck -2 -m -p $prefix.$pedig.level.1.memissing.ped -n $prefix.marker -b $prefix.$pedig.level.2
    
	$java -Xmx10G -cp $javacp SetLinkageFileMEMissingPedCheck2 $prefix.$pedig.level.1.memissing.ped $prefix.marker $prefix.$pedig.level.2.pedcheck.err $prefix.$pedig.level.2.memissing.ped $prefix.$pedig.level.2.pedcheck.mestat

	#java -Xmx10G -cp $javacp ConvertPedToGIGILongFormat $pedig $seqfam $prefix.$pedig.level.2.memissing.ped $prefix.marker $prefix.GIGI.genotype.$pedig

	gzip $prefix.$pedig.ped
	gzip $prefix.$pedig.level.1.pedcheck.err
	gzip $prefix.$pedig.level.1.memissing.ped
	gzip $prefix.$pedig.level.2.pedcheck.err
	gzip $prefix.$pedig.level.2.memissing.ped

    done < $familyfile
    #java -Xmx10G -cp $javacp MergeGIGIFile $familyfile $prefix.GIGI.genotype
    #java -Xmx10G -cp $javacp MergePedCheckMEStatFile $familyfile $prefix $prefix.GIGI.genotype.ME.stat.txt
    #java -Xmx10G -cp $javacp ConvertGIGIOutputVCF $prefix.GIGI.genotype.merged.txt.gz $vcf $prefix.me.vcf.gz
done

# Merge all family output files into one file and add position info if not already there?
#java -Xmx10G -cp $javacp MergeGIGIFile $familyfile $prefix/GIGI.genotype.chr.$chr

#java -Xmx10G -cp $javacp MergePedCheckMEStatFile $familyfile $prefix $outdir/GIGI.genotype.ME.stat.chr.$chr.txt

#java -Xmx10G -cp $javacp ConvertGIGIOutputVCF $outdir/GIGI.genotype.chr.$chr.merged.txt $vcf $dir/chr$chr.me.vcf

#/u/project/zarlab/jhsul/bin/bam_to_fastq/bam_to_fastq_3
